### ISSUE TITLE
Automatically deploy helm-charts to Nexus on PR merges

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/helm-charts#227]
We need to get back to automatically publishing helm charts to https://nexus.production.deciphernow.com/#browse/browse:helm-hosted. Also, there were updates to a charts in https://github.com/DecipherNow/helm-charts/pull/216 and we need to manually publish to get up to date.

**Comment by chrisbsmith** [comment]
@tilleryd @moosecanswim i believe we can close this issue now.  concur?
