### ISSUE TITLE
Deploy ESS to WISARD Namespace

### ISSUE THREAD

**Issue by moosecanswim** [DecipherNow/helm-charts#231]
- Deploy ESS to wisard namespace with a 3 ES cluster.
- Add ESS to Catalog

@bmheadley  Lets work on this together.  we did a deployment last week for AFRL and this will be pretty similar but to a different namespace.

**Comment by chrisbsmith** [comment]
@bmheadley @moosecanswim what's the status on this?  This is an issue that can be worked/investigated while I am away.

**Comment by moosecanswim** [comment]
Complete

**Comment by chrisbsmith** [comment]
@moosecanswim  please link the BitBucket PR here

**Comment by moosecanswim** [comment]
https://bitbucket.di2e.net/projects/GREYMATTER/repos/helm-charts/pull-requests/64/diff
