### ISSUE TITLE
Permission errors in slo service

### ISSUE THREAD

**Issue by kaitmore** [DecipherNow/helm-charts#268]
Starting the slo service using the minikube setup on the `release-2.0` branch results in an error in the slo container:

```
Logging initialized at error level.

(node:1) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, open '/certs/ca.pem'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.getSSLConfig [as default] (/etc/gm-slo/dist/util/sslConfig.js:29:34)
    at Object.<anonymous> (/etc/gm-slo/dist/db.js:45:44)
    at Generator.next (<anonymous>)
    at /etc/gm-slo/dist/db.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/etc/gm-slo/dist/db.js:3:12)
    at Object.connectToSLODB (/etc/gm-slo/dist/db.js:41:12)
    at Object.<anonymous> (/etc/gm-slo/dist/index.js:18:6)```

**Comment by justincely** [comment]
I got this on EKS (kubernetes on amazon) as well.  I get a little further by forcing the SLO container to run as root:
```
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
```

but then get to another error:

```
Logging initialized at error level.

Connecting to SLO DB.
error: Error: The server does not support SSL connections
error: Could not establish initial connection to DB. Exiting.
```

Postgres doesn't log anything that i see as unusual.  Any idea where this log message is coming from?

**Comment by tilleryd** [comment]
It looks like I over-optimized for Openshift when getting SSL working for Postgres in OpenShift.

The postgres-slo-overrides configMap expects a path to exist within an OpenShift Postgres container.
```
# These override configs in OpenShift's postgres container located at /var/lib/pgsql/data/userdata/postgresql.conf
```

If we deploy to anything other than OpenShift the path won't be there.

**Comment by justincely** [comment]
best fix i've got right now is to add security context to our images.  I believe this is due to us declaring users in our dockerfiles, which conflicts with raw k8s defaulting to running/mounting files as root.

```
      securityContext:
        runAsUser: 2000
        runAsGroup: 0
        fsGroup: 2000
```

fixes coming in a pr soon
