### ISSUE TITLE
Mesh cannot recover from minikube(shift) stop and restart

### ISSUE THREAD

**Issue by justincely** [DecipherNow/helm-charts#277]
1. Deploy mesh according to instructions.
2. <play with mesh>
3. `minikube stop`
4. `minikube start`

Much of the mesh comes back fine after #3, but a few things, gm-control-api, data, etc cannot recover into a working state.  

To recover:
1. purge helm installs for `greymatter` and `voyager`.
2. `helm dep up greymatter`
3. re-install `greymatter` and `voyager`
4. `minikube service --https=true voyager-edge`

**Comment by justincely** [comment]
@jdholmes1978 hit this as well

**Comment by chrismholmes** [comment]
Hmmm a reinstall every time you start and stop?  That’s not good.

**Comment by jdholmes1978** [comment]
Isn't this ticket duplicative of issue: https://github.com/DecipherNow/gm-catalog/issues/234
