### ISSUE TITLE
cannot upload to gm-data in current minishift docs

### ISSUE THREAD

**Issue by justincely** [DecipherNow/helm-charts#278]
I cannot create my user's directory; which is because the `GMDATA_USERFIELD` is set to `userDN` (https://github.com/DecipherNow/helm-charts/blob/release-2.0/data/values.yaml#L99) but the JWT user's file has no `USERDN` attribute: (https://github.com/DecipherNow/helm-charts/blob/release-2.0/jwt/values.yaml#L100)

This needs to be changed such that either:
1) GMDATA_USERFIELD is `email` since it already exists in JWT as an available attribute
2) each JWT user needs an added `USER_DN` field. 

I prefer the former, as it's easier to use.

**Comment by justincely** [comment]
no matter what I try, i can't seem to get my local instance to actually change from `userDN` to `email` in this line https://github.com/DecipherNow/helm-charts/blob/release-2.0/data/values.yaml#L99.  No matter what I do, the deployed pod still sets `GMDATA_NAMESPACE_USERFIELD: userDN
`

**Comment by justincely** [comment]
@kaitmore and @tilleryd got me squared away

**Comment by chrismholmes** [comment]
Can we document the issue and the conclusion?

**Comment by tilleryd** [comment]
@chrismholmes I created https://github.com/DecipherNow/helm-charts/issues/281 to circle back around and document this.
