### ISSUE TITLE
Dashboard should only show major.minor version numbers

### ISSUE THREAD

**Issue by chrisbsmith** [DecipherNow/helm-charts#315]
The dashboard should only show a major.minor version for all services.  For the Grey Matter services, an update to the [services.json](https://github.com/DecipherNow/helm-charts/blob/release-2.0/catalog/json/services/service.json).  

Possible solution will be to use a Sprig template to split the version string at the `.`'s and then only use the first two values.

Possible similar to, or closes #192

**Comment by chrismholmes** [comment]
No.  This is not accurate.  Dashboard should display major.minor.minor

**Comment by chrisbsmith** [comment]
Well that’s the fastest ticket I've ever closed.
