### ISSUE TITLE
GM Data should be a StatefulSet instead of a Deployment

### ISSUE THREAD

**Issue by chrisbsmith** [DecipherNow/helm-charts#318]
When I attempted to roll the internal GM Data to a new version, the update failed until I deleted the prior deployment configuration.  This failure is caused because the internal data uses a PVC for local storage.  Since Deployments turn on the new pod before deleting the old pop, the new internal-data pod failed to start because it was unable to attach the PVC.  StatefulSets assume a PVC is attached and shut down the initial pod and then deploy a new pod.

**Comment by whenhellfreezes** [comment]
Merged a PR that fixes.
