### ISSUE TITLE
Cleanup up minikube doc

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/helm-charts#347]
_Originally posted by @tilleryd in https://github.com/DecipherNow/helm-charts/pull/341/files/103b6d83088d282cfe77a2215b2780f1ea8688b4_

These instructions should no longer include references to the deleted `greymatter-minikube.yaml` file:
```
- [greymatter-minikube.yaml](../greymatter-minikube.yaml) provides Minikube specific configurations but requires no changes
  
Copy these files to `custom-greymatter.yaml`, `custom-greymatter-secrets.yaml` and `custom-greymatter-minikube.yaml`.
```

**Comment by danielpcox** [comment]
I just ran into this. Since that file was deleted in https://github.com/DecipherNow/helm-charts/pull/341 it should be removed from the docs that reference it.
