### ISSUE TITLE
Update Prometheus Service Account

### ISSUE THREAD

**Issue by chrisbsmith** [DecipherNow/helm-charts#362]
We create a `prometheus-sa` but we assign the `control-sa` service account to prometheus.  

https://github.com/DecipherNow/helm-charts/blob/c71db206edf22ec203533f9fba15ed4fd286f8d6/greymatter-service-accounts.yaml#L18-L22

https://github.com/DecipherNow/helm-charts/blob/93cc57999f5847bc908b846621f9bf6f645c2eb0/dashboard/templates/prometheus.yaml#L18

The two SAs have almost identical resource and verb requirements in their role bindings:

`control-sa`
https://github.com/DecipherNow/helm-charts/blob/c71db206edf22ec203533f9fba15ed4fd286f8d6/greymatter-service-accounts.yaml#L52-L60

vs `prometheus-sa`
https://github.com/DecipherNow/helm-charts/blob/c71db206edf22ec203533f9fba15ed4fd286f8d6/greymatter-service-accounts.yaml#L149-L157

**except** the `control-sa` is uses a `ClusterRoleBinding` to bind the role to the SA.  This grants control, and apparently prometheus, cluster wide permissions to `get`, `list`, and `watch` pods and endpoints.  This is probably the desired intent, but we should either remove the `prometheus-sa` from our list of required SAs or update this reference in the Prometheus deployment.

@justincely @tilleryd  @joshua-rutherford

**Comment by whenhellfreezes** [comment]
Does prometheus need to look across namespaces? @chrisbsmith

**Comment by jdholmes1978** [comment]
@chrisbsmith why wouldn’t we use the sidecar to do this vice using a K8 capability’s. We can use the RBAC features.

**Comment by chrisbsmith** [comment]
@jdholmes1978 this update to the service account allows the sidecar to scrape the Metrics from the sidecar to be sent to Prometheus. If there is another way we need to test it first

**Comment by chrismholmes** [comment]
How do we send the metrics to Prometheus?  Via a Prometheus API call?  If that is the case I think what Jon is saying is that we can wrap the Prometheus API in the mesh and use our RBAC security to enable the communication.  This would be a repeatable pattern on or off K8s as opposed to right now we are relying on K8s RBAC here and that may not always be there.

**Comment by chrisbsmith** [comment]
So my above comment is incorrect.  We don't _send_ any metrics to Prometheus.  Instead, Prometheus is configured to scrape the `8081` port from each sidecar.  This issue was just to fix how we are building out the prometheus service account.  Currently, the code configured Prometheus with the `control-sa` rather than the `prometheus-sa`.  

I'm sure we can modify how we collect metrics for Prometheus to have the sidecars send to prometheus rather than a scrape, but that's not what we're currently doing so we'd have to run this through the test process before implementing here.

**Comment by chrisbsmith** [comment]
Adding @tilleryd and @dgoldstein1 in case I didn’t explain it correctly

**Comment by tilleryd** [comment]
Prometheus service discovery leverages the k8s REST API, not Envoy. It discovers pods, containers and scrape targets at specified ports and routes. There will always be a dependency on the platform unless we create an abstraction layer, which is not worth the effort IMHO.

**Comment by dgoldstein1** [comment]
@chrisbsmith 
> Prometheus is configured to scrape the 8081 port from each sidecar

Yes, currently. We can reconfigure this to scrape from different k8 object types as well see [docs](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config). This would change the SA needed.

> I'm sure we can modify how we collect metrics for Prometheus to have the sidecars send to prometheus rather than a scrape, but that's not what we're currently doing so we'd have to run this through the test process before implementing here.

No, unfortunately this is _not possible_, and one of the biggest downsides of prometheus.

@tilleryd 
> Prometheus service discovery leverages the k8s API, not Envoy

Yes, although if the metrics are served over https, prometheus will need authentication. 

```
  # This TLS & bearer token file config is used to connect to the actual scrape
  # endpoints for cluster components. This is separate to discovery auth
  # configuration (`in_cluster` below) because discovery & scraping are two
  # separate concerns in Prometheus.
``` 
from [this example](https://raw.githubusercontent.com/prometheus/prometheus/v1.1.0/documentation/examples/prometheus-kubernetes.yml)

Why not just create an additional sa for prometheus?

**Comment by tilleryd** [comment]
Ok, now that I've stewed on this a bit, I see that @chrismholmes is talking about our hybrid platform support. We "could" deploy Prometheus with our sidecar, and configure read-only RBAC rules on the k8s REST API. Prometheus service discovery will still be tightly coupled to the platform but this will alleviate the need for declarative service account configuration.

**Comment by joshua-rutherford** [comment]
I think that the attention this pull request has gotten is a bit unwarranted.  

In a Kubernetes deployment the preferred method of discovery for Prometheus is the Kubernetes API.  The Kubernetes API does not allow anything to read from that API without an RBAC policy in place.  Adding our sidecar between Prometheus and the Kubernetes API will not alleviate the need for this change in anyway.

The only thing that might change this is if we implemented a new Prometheus discovery mechanism that relies upon the Grey Matter Control Plane.  While this is probably worth investigating as it will normalize Grey Matter deployments a bit it is not a trivial thing to do and would require planning.

**Comment by whenhellfreezes** [comment]
Set the service account to point to the prometheus specific service account and changed the prometheus role to be a cluster role so that it can look across namespaces. This change is in line with the original request. Didn't see the added comments until just now. Assuming that a new feature that allows prometheus to do service discovery through gm control will be out of scope at the moment.
