### ISSUE TITLE
Investigate catalog-init script

### ISSUE THREAD

**Issue by kaitmore** [DecipherNow/helm-charts#376]
Catalog will occassionally start up without all the configured services:

![image](https://user-images.githubusercontent.com/22768918/68127967-e507c100-fee4-11e9-8896-d3f376e9ceb3.png)

**Comment by tilleryd** [comment]
Need to dig into the catalog-init job https://github.com/DecipherNow/helm-charts/blob/release-2.1/catalog/templates/catalog-init.yaml

**Comment by chrisbsmith** [comment]
This _may_ be an issue caused by the lag of catalog persisting data to GM Data.  The `curl` commands that issue the init job are kind of fire and forget.  They don't retry, rather they fail and the entire script should exit.

The actual script is located here: https://github.com/DecipherNow/helm-charts/blob/release-2.1/catalog/config/bootstrap.sh

**Comment by kaitmore** [comment]
@chrisbsmith @tilleryd @danielpcox 

After investigating and trying various fixes, I've concluded that the catalog-init script is not the issue here. My first approach was to modify the script to retry until the request succeeds, however, I still occasionally saw missing services in the dashboard. 

In the following case it was the JWT service. You can see the successful 200 response from catalog here after running the catalog-init job:

```
Found service: jwt-security/
< HTTP/1.1 200 OK
< Content-Type: application/json
< X-Request-Id: 
< Date: Fri, 22 Nov 2019 21:21:51 GMT
< Content-Length: 27
< 
{ [27 bytes data]

100   473  100    27  100   446   1588  26235 --:--:-- --:--:-- --:--:-- 27823
* Connection #0 to host catalog left intact
Creating catalog item service.json
Contents of service.json...

{
  "clusterName": "jwt-security",
  "zoneName": "zone-default-zone",
  "name": "Grey Matter JWT Security",
  "version": "0.2.0",
  "owner": "Decipher",
  "capability": "Grey Matter",
  "runtime": "GO",
  "documentation": "",
  "prometheusJob": "",
  "minInstances": 1,
  "maxInstances": 1,
  "authorized": true,
  "clusterID": "",
  "meshID": "",
  "enableInstanceMetrics": true,
  "enableHistoricalMetrics": true,
  "metricsTemplate": "",
  "metricsPort": 8081
}
Uploading service.json...

* TCP_NODELAY set
* Connected to catalog (10.104.127.197) port 9080 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/ca.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [222 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [64 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [1718 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [300 bytes data]
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
{ [434 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
} [5047 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [37 bytes data]
* TLSv1.2 (OUT), TLS handshake, CERT verify (15):
} [264 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=*.greymatter.svc.cluster.local; OU=Engineering; O=Decipher Technology Studios; L=Alexandria; ST=Virginia; C=US
*  start date: Feb 23 16:40:05 2019 GMT
*  expire date: Feb 20 16:40:05 2029 GMT
*  issuer: C=US; ST=Virginia; O=Decipher Technology Studios; OU=Engineering; CN=Decipher Certificate Authority (Intermediate); emailAddress=engineering@deciphernow.com
*  SSL certificate verify ok.
> POST /clusters HTTP/1.1
> Host: catalog:9080
> User-Agent: curl/7.61.1
> Accept: */*
> Content-Length: 445
> Content-Type: application/x-www-form-urlencoded
> 
} [445 bytes data]
* upload completely sent off: 445 out of 445 bytes

100   445    0     0  100   445      0    369  0:00:01  0:00:01 --:--:--   369< HTTP/1.1 200 OK
< Content-Type: application/json
< X-Request-Id: 
< Date: Fri, 22 Nov 2019 21:21:53 GMT
< Content-Length: 25
< 
{ [25 bytes data]

100   470  100    25  100   445     12    218  0:00:02  0:00:02 --:--:--   230
100   470  100    25  100   445     12    218  0:00:02  0:00:02 --:--:--   230
* Connection #0 to host catalog left intact

200
```

I turned on verbose logging in the catalog service and found something interesting:

```
{"level":"debug","service":"gm-catalog","package":"instance","zoneName":"zone-default-zone","clusterName":"jwt-security","time":"2019-11-22T21:21:53Z","message":"SetClusterData"}
{"level":"debug","service":"gm-catalog","handler":"clustersHandler","method":"POST","x-request-id":"","URI":"/clusters","Added":"jwt-security","time":"2019-11-22T21:21:53Z","message":"clustersPost"}
{"level":"debug","service":"gm-catalog","package":"instance","zoneName":"zone-default-zone","clusterName":"jwt-security","time":"2019-11-22T21:21:53Z","message":"RemoveClusterData"}
```

You can see that the cluster is successfully added but then something triggers an immediate removal, which confirms to me that it's not our script. I talked to @bcmendoza and he had a suspicion that catalog is not writing to data correctly.

Another thing to note is that I couldn't recreate this with catalog@1.0.1.

**Comment by chrisbsmith** [comment]
Whew @kaitmore.  This makes me feel a little better about my bash script.  ha.

Thanks for the thorough write up.  That sort of lines up with my suspicion that the error is caused by the delay that it takes catalog to write the update to GM Data.  

Can you try another test?  Can you set up Catalog **not** to use GM Data for persistence?  Instead, configure Catalog to persist the data locally, or not at all.  I'd like to see if there's a possible delay in persisting catalog data to GM Data and if that's the possible cause.

**Comment by bcmendoza** [comment]
I was surprised to see that our Helm charts are using Catalog v1.0.2 since @justincely had identified a bug in that release (https://github.com/DecipherNow/gm-catalog/issues/236) and reverted back to v1.0.1 in all our live deployments. Our Helm charts should be updated to use v1.0.1 until we can release a patch for Catalog that addresses both issues.

**Comment by chrisbsmith** [comment]
@bcmendoza you have identified a glaring gap in our communication and process for notifications of new releases. I don’t know that I was made aware to roll back. Maybe we need an automated process to open an issue the helm charts repo. This is a completely separate soap box

Can you expand upon the issue that causes Justin to roll back versions?  Is it related to this issue?

@kaitmore can you try with 1.0.1?

**Comment by kaitmore** [comment]
@bcmendoza Thanks Brian. I had no idea that we weren't supposed to update to 1.0.2.

**Comment by kaitmore** [comment]
@chrisbsmith I have tried it with 1.0.1 and could not recreate the issue

**Comment by chrisbsmith** [comment]
@joshua-rutherford @justincely if catalog 1.0.2 is bad, should we delete it from nexus?

**Comment by joshua-rutherford** [comment]
1. We can never unrelease something (i.e., delete it from nexus). You cannot know the downstream effects of such an action so it's just not allowed.  
1. When a bug is discovered in released code of this level we need to prioritize the fix immediately.  I suspect this was not prioritized as it was seen as an edge case (i.e., scaling to zero) but all services start at zero so it's only an edge case after launch.  It is the case on launch.

I need an estimate on the work required for the linked issue Justin opened.

**Comment by bcmendoza** [comment]
@joshua-rutherford After investigating in Catalog, I think I can have this addressed in 2 days. There were some other things @kaitmore reported that I'm a bit concerned about re: writing to gm-data so I'll need to test if the issues are related.

**Comment by kaitmore** [comment]
Closing, issue is being tracked in https://github.com/DecipherNow/gm-catalog/issues/248

**Comment by kaitmore** [comment]
Closing, issue is being tracked in https://github.com/DecipherNow/gm-catalog/issues/248
