### ISSUE TITLE
Control incorrectly versioned

### ISSUE THREAD

**Issue by chrisbsmith** [DecipherNow/helm-charts#394]
Since we're still developing on the `release-2.1` branch, the version for all packages should be `2.1.X`.

Also needs to be updated in `greymatter/requirements.yaml`

https://github.com/DecipherNow/helm-charts/blob/8e883c3b4a9a0bcd948a909f19782215a4b1a992/control/Chart.yaml#L5

**Comment by whenhellfreezes** [comment]
Can this be closed @chrisbsmith @kaitmore ?
