### ISSUE TITLE
Securing impersonation by default

### ISSUE THREAD

**Issue by danielpcox** [DecipherNow/helm-charts#396]
Two changes must be made in `helm-charts` to remove an impersonation security hazard:

1. We must enable `gm.impersonation` on every sidecar that will ever receive a request through `edge`, with `edge`'s DN in the whitelist. (We also want to include in the whitelist any other internal service's unique DN that will need to impersonate users.)
2. `edge` must have a unique certificate, so we can confirm that the incoming request (with a request to impersonate a user) is actually coming from `edge`. Same thing for any other internal service that needs to be able to impersonate users.
3. Until [gm-proxy#594](https://github.com/DecipherNow/gm-proxy/issues/594) is fixed, mTLS must be turned on between `edge` and all services that make use of `USER_DN` (such as Data).

**Comment by chrisbsmith** [comment]
For #3, the current Helm charts deploy Grey Matter with mTLS enabled by default.

The other two will  require updates to the code.
