### ISSUE TITLE
Add ability to use individual certs for each sidecar

### ISSUE THREAD

**Issue by chrisbsmith** [DecipherNow/helm-charts#397]
Currently, the helm charts use the [sidecar_volumes](https://github.com/DecipherNow/helm-charts/blob/release-2.1/greymatter/templates/_sidecar_volumes.tpl) and [sidecar_volume_mounts](https://github.com/DecipherNow/helm-charts/blob/release-2.1/greymatter/templates/_sidecar_volume_mounts.tpl) templates for loading the certificates into the each sidecar.  The issue with this pattern is that all sidecars will then load in the same certs and it's impossible to create a specific cert for an individual service (ie: GM Data).  

The greymatter-secrets file will probably become even bigger as new certificates for each sidecar will be required, but this will allow us to issue service specific certs from the same CA, which enhances our ability to do impersonation and whitelisting.

**Comment by chrisbsmith** [comment]
For now, Edge is the only proxy that needs the ability to take in a unique certificate.  Others will be migrated later.

**Comment by tilleryd** [comment]
@chrisbsmith Is this still an issue? Looks like if `global_certs.enabled` is false, then individual charts load up their own sidecar certs.

**Comment by chrisbsmith** [comment]
My idea was to have the charts build a unique very doe each service. However, the spire initiative will cover this issue. 

I'm good to close this issue
