### ISSUE TITLE
missing SDS resources in spire

### ISSUE THREAD

**Issue by zoemccormick** [DecipherNow/helm-charts#421]
Updated branch for this error from https://github.com/DecipherNow/greymatter/issues/172 .  Based off of this branch https://github.com/DecipherNow/helm-charts/tree/another-spire.

With our current setup, if we run `minikube start -p gm-deploy-1 --memory=4096 --cpus=4 --extra-config=kubelet.authentication-token-webhook=true` and install the local helm charts on this branch as usual, port forward the edge pod to 8001:8001 and `curl localhost:8001/certs`, the  spiffe certs are there.  In the spire-agent logs, we still see: 

```
time="2019-12-02T14:42:54Z" level=debug msg="Received StreamSecrets request" nonce=c446f80a resource_names="[spiffe://deciphernow.com/edge/mTLS]" subsystem_name=sds_api version_info=
time="2019-12-02T14:42:54Z" level=error msg="Envoy reported errors applying secrets" error="Missing SDS resources for spiffe://deciphernow.com/edge/mTLS in onConfigUpdate()" resource_names="[spiffe://deciphernow.com/edge/mTLS]" subsystem_name=sds_api
time="2019-12-02T14:42:54Z" level=error msg="Client rejected expected version and rolled back" expect=1 subsystem_name=sds_api version_info=
```

**Comment by zoemccormick** [comment]
no change to configuration of the secrets themselves (subject_alt_names, etc - following this https://github.com/DecipherNow/greymatter/issues/74 ), seems to change this, nor does tweaking the configurations for the workload attestation. My observations recently:
1. run as above and exec into the spire-agent pod `kubectl exec -it {spire-agent-pod} /bin/sh` and run `/opt/spire/bin/spire-agent api fetch -socketPath /run/spire/sockets/agent.sock` - as is we see `rpc error: code = PermissionDenied desc = no identity issued` in response
2. purge the installation and change these two lines [here](https://github.com/DecipherNow/helm-charts/blob/6464ff8255a5082a19bfc0ae4269ceb0757a9985/spire/config/setup.sh#L57-L58) to `-selector unix:uid:0 \`, run again, exec into the agent pod and run the same command, now we see the entries.  I am currently trying to figure out the implications of this - as we do see [here](https://github.com/spiffe/spire/blob/master/doc/spire_agent.md#envoy-sds-support) that SDS is served over the same unix domain socket as the workload api

**Comment by zoemccormick** [comment]
@rfielding @cstrahan  I am writing this up here so we don't lose it in slack.

This error appears to be from the selectors here https://github.com/DecipherNow/helm-charts/blob/6566425a74094e11f9b0cf91932d5c250e827779/spire/config/setup.sh#L57-L58.  You can view the changes made in spire-testing-3 (it's messy, I know) for exactly what I am using the get this running.  At the bottom of this comment I am going to include a new setupec2 script that I modified from rob to run exactly this.  

Basically, what I think the problem was is the selector for workload attestation was looking for workloads with k8s:pod-label:app:edge when trying to find the svid with id spiffe://deciphernow.com/edge/mTLS, but since they weren't coming from this pod, they were getting blocked.  They are in the same namespace in this setup, default, so the selector k8s:ns:default will allow them.

To explain the setup I have and how to test some things in spire-testing-3:

1. The edge-to-service clusters are passing a secret config, specifically spiffe://deciphernow.com/edge/mTLS.  What I believe is/should be happening here is it is setting spiffe on the service-x ingress from edge looking for that id.  Then, the edge listener has the same secret config set, which again i think is setting the edge egress.  You can see these configs when it's running in the cli ( I was port-forwarding the gm-control-api-0 pod, and setting GREYMATTER_API_HOST=localhost:5555 and using greymatter cli in my ec2).   No SSL Configs are being passed in api objects in this setup.

2. Now, as I stated above run `kubectl exec -it {spire-agent-pod} /bin/sh` and run `/opt/spire/bin/spire-agent api fetch -socketPath /run/spire/sockets/agent.sock` you should be able to see the spiffe entries whereas before we couldn't (I think this is also because the spire-agent is in the default namespace but the selector for pod label was blocking it as well). There should be no `missing SDS resources` errors in the spire-agent logs or the proxy logs.

Note that I needed the more recent gm-control than what Is used in the helm-charts, so I pushed a new gm-control build to docker hub and pulled it into my ec2, altered the image in greymatter.yaml (these steps are in my script).

```
#!/bin/bash
(
if [ -d helm-charts ]
then
  echo already cloned helm
else
  git clone https://github.com/DecipherNow/helm-charts.git
  cd helm-charts
  git checkout spire-testing-3
fi
)

sudo rm -rf minikube-linux-amd64*
sudo minikube delete
sudo snap remove helm
sudo snap remove kubectl
sudo apt-get remove -y docker.io
#sudo rm -rf /home/ubuntu/.helm
source ./credsenv
sudo apt update
sudo apt install docker.io socat -y
sudo snap install kubectl --channel=1.6/stable --classic
curl -LO https://git.io/get_helm.sh
chmod 700 get_helm.sh
./get_helm.sh --version v2.15.2

sudo docker login
sudo docker pull deciphernow/gm-control:spire
#sudo snap install helm --channel=2.16/stable --classic
#sudo curl -fSL https://storage.googleapis.com/kubernetes-helm/helm-v2.12.3-linux-amd64.tar.gz | tar xz -C /usr/local/bin/ --strip-components=1 linux-amd64/helm 
wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
chmod +x minikube-linux-amd64
sudo mv minikube-linux-amd64 /usr/local/bin/minikube
sudo  minikube start --vm-driver=none --memory 16384 --cpus 6 --kubernetes-version='v1.15.5' #--extra-config=kubelet.authentication-token-webhook=true
sudo helm init
sleep 60
sudo kubectl get pods -n kube-system
sudo helm repo add appscode https://charts.appscode.com/stable/
sudo helm repo update
sudo helm install appscode/voyager --name voyager-operator --version 10.0.0 \
  --namespace kube-system \
  --set cloudProvider=minikube \
  --set enableAnalytics=false \
  --set apiserver.enableAdmissionWebhook=false
sleep 60
sudo kubectl get pods -n kube-system
sudo helm repo add decipher https://nexus.production.deciphernow.com/repository/helm-hosted --username $NEXUS_USER --password $NEXUS_PASSWORD
(
  cd helm-charts
  sudo rm -rf greymatter/charts
  sudo helm dep up greymatter
  sudo helm repo update
  sudo helm install greymatter -f custom-greymatter.yaml -f custom-greymatter-secrets.yaml -f greymatter-service-accounts.yaml --name gm --set global.k8s_use_voyager_ingress=true
)
sleep 60
sudo kubectl get pods
sleep 60
sudo kubectl get pods
sleep 240
sudo kubectl get pods
sudo minikube service list
```

**Comment by justincely** [comment]
@zoemccormick what's the status of this?  It seems old and obsolete?

**Comment by zoemccormick** [comment]
@justincely this was never closed because we never merged in the working spire branch

**Comment by zoemccormick** [comment]
closing as a working SPIRE implementation is in release-2.2 of the helm charts
