### ISSUE TITLE
mongo fails in eks

### ISSUE THREAD

**Issue by dgoldstein1** [DecipherNow/helm-charts#449]
we currently cannot specify both `eks` and `kubernetes` as `global.environment` at the same time, although we need the values for aws to be:
-  `eks ` for volumes to mount properly
- `kubernetes` for ingress to work

commit = `1ca35048f4695e93559b81b1bb44d158174c4084`

**Comment by chrisbsmith** [comment]
@dgoldstein1 can you please provide the yaml from `kubectl get ingress -n greymatter edge-ingress.yaml -o yaml`

**Comment by tilleryd** [comment]
It worked for me by setting the below in greymatter.yaml.

```
        ingress.appscode.com/type: LoadBalancer
```

**Comment by dgoldstein1** [comment]
@tilleryd thanks, this solves the ingress issue :heavy_check_mark: 

The global.environment problem still isn't resolved. I'm going to rename this issue to that and resolve in a separate pull request
