### ISSUE TITLE
The edge’s dashboard name should be configurable

### ISSUE THREAD

**Issue by chrisbsmith** [DecipherNow/helm-charts#467]
we need the ability to provide a different name for the edge as displayed in the dashboard, specifically for customer installations. 

Default value should continue to be “Grey Matter Edge” unless the user modifies the config value

**Comment by whenhellfreezes** [comment]
`helm install ******** --set global.services.edge.name="Elephant"` would do the trick I think. Or should that option be either more discoverable or intuitive?

**Comment by sofiashalotenko** [comment]
This is already done. Closing.
