### ISSUE TITLE
Allow for use of existing certificate secrets

### ISSUE THREAD

**Issue by chrisbsmith** [DecipherNow/helm-charts#470]
Currently, we require that the users provide the plain text values for certificates for Grey Matter in `greymatter-secrets.yaml`.  While this has its benefits, it is very error prone when needing to update any of the certificate values (ca, cert, key).  

It would be useful to allow the users to create their certificate secrets (and there are many) in Kubernetes and to reference them from the Helm Charts.

This would be one less sensitive piece of data that we would have to worry about storing in a git repo and would reduce the complexity of modifying the certificate values.

In making this change, we need to have very clear instructions on how we expect the secret to look in Kubernetes (ie: with files called `ca.crt`, `server.crt` and `server.key` [NOTE: these may be different for different services])

**Comment by sofiashalotenko** [comment]
This is already done in the release-2.2 branch.  Closing.
