### ISSUE TITLE
Update default image pull secret

### ISSUE THREAD

**Issue by bmheadley** [DecipherNow/helm-charts#483]
When deploying data the ImagePullSecret is 'docker-greymatter-ro', it should default too 'docker.secret'.

**Comment by chrisbsmith** [comment]
In some cases, the "receiving environment" may have a predefined image pull secret.  In that case, the charts should actually allow for the user to pass the name of an already created secret.  

This should be reflected across all of the services helm charts. You can move this issue to an epic and create new issues for each chart

**Comment by bmheadley** [comment]
OBE based on discussion with @chrisbsmith on 3/11. New Helm Charts will use a helm chart to deploy the secrets to a namespace and then have a default value defined in the values file, which was the necessary action here.
