### ISSUE TITLE
Setting sidecar.create_sidecar_secret to false did not have intended result

### ISSUE THREAD

**Issue by chrisbsmith** [DecipherNow/helm-charts#488]
When deploying Grey Matter to a new namespace, the sidecar-certs secret was already created in the namespace, so I set `sidecar.create_sidecar_secret` to `false`. However, when running a `helm install`, the install failed because it still tried to build the sidecar-certs secret.

**Comment by tilleryd** [comment]
Initially reported in https://support.deciphernow.com/a/tickets/180
