### ISSUE TITLE
update charts for release 1.2

### ISSUE THREAD

**Issue by justincely** [DecipherNow/helm-charts#500]
The charts need to be updated to the release 1.2 candidates, update necessary config/env-vars, and best practices.

**Comment by chrisbsmith** [comment]
As you’re working on the updates, please keep in mind that we need a test case for upgrades from Grey Matter deployed with prior versions of the Helm Charts. 

We can’t assume that we will only just use the charts for installs only

**Comment by justincely** [comment]
Closing with the work so far, going to be a new issue in the future with more specifics for the final release of 1.2
