### ISSUE TITLE
Refactor secrets

### ISSUE THREAD

**Issue by kaitmore** [DecipherNow/helm-charts#504]
As a part of the helm charts restructure we are going to change how secrets are handled. Instead of requiring secrets in greymatter-secrets.yaml, our charts and values files will simply expect the name of a secret resource.

We will also need a generic helper script that makes creating all these secrets easier.

- Remove greymatter-secrets.yaml
- Remove all secret files
- Update values.yaml files
- Create helper script

**Comment by chrisbsmith** [comment]
Perfect.  Thanks @kaitmore .  The install instructions need to be very clear about this and provide instructions for how to create the secrets if they don't exist.  

Note that we create a bunch of secrets, mostly TLS secrets for each service.  In some environments we use the same cert throughout the configuration.  This means that we've created the same secret multiple times.  SPIFFE/SPIRE will solve this issue for us eventually, but for now, it may make sense to ask the customer if they want to use unique certs for each service.  If the answer is no, then we could reference the single secret in all cases.

**Comment by kaitmore** [comment]
Closed by #509
