### ISSUE TITLE
certificates link to quickstart

### ISSUE THREAD

**Issue by moosecanswim** [DecipherNow/helm-charts#519]
Certificates section has a bad link to quickstart certs.

Issue is on this page:
https://github.com/DecipherNow/helm-charts/blob/release-2.1/docs/Getting%20Started.md#certificates

This is the dead link: [DecipherNow/grey-matter-quickstart](https://github.com/DecipherNow/grey-matter-quickstarts)

**Comment by chrisbsmith** [comment]
well damn, I just archived that link.  Can you please remove it. and point it locally.

**Comment by moosecanswim** [comment]
https://github.com/DecipherNow/helm-charts/pull/521
