### ISSUE TITLE
The Grey Matter Control K8s Label should be configurable

### ISSUE THREAD

**Issue by chrisbsmith** [DecipherNow/helm-charts#539]
The kubernetes label that Grey Matter Control uses to identify services in the mesh should be configurable.  While the below environment variable attempts to expose this, the pod definitions are still hard coded for `gmproxy`.  

Ideally, we want to make sure the label is specific to Grey Matter.  I'm inclined to use `greymatter.io/control` for our label.

https://github.com/DecipherNow/helm-charts/blob/a58821c4beed915befbd9de0d5d11f9680ecabdb/fabric/values.yaml#L116

Here is an example at the edge where the label key is hard coded.

https://github.com/DecipherNow/helm-charts/blob/a58821c4beed915befbd9de0d5d11f9680ecabdb/edge/templates/edge.yaml#L10

For the Helm updates, you could possibly look at using a template file to build the pod labels.

**Comment by zoemccormick** [comment]
closed with #585
