### ISSUE TITLE
Add observables to default charts

### ISSUE THREAD

**Issue by justincely** [DecipherNow/helm-charts#556]
1. deploy ELK
2. setup observables on all sidecars
3. expose Kibana UI at `/core/observables`

**Comment by chrisbsmith** [comment]
@justincely we've never brought ELK with us because we were told that we should not assume users will want to deploy it.  Has guidance changed?  We have a helm chart (in customer land) that will already deploy ELK.  We could move this over if you want.

**Comment by joshua-rutherford** [comment]
Our "Grey Matter" chart should only turn on the observables filter and point to an externally deployed Kafka instance.  We have to draw lines around things better here.

I know that we are asked to deploy the stack all the time and we do need a way to do that, but we need to accept that deploying this stuff is multistep and pluggable.  If you want to use the ELK stack with Kafka, you have to come to the table with Kafka.  If we are deploying it for a customer, we can do that for them with separate charts.

**Comment by joshua-rutherford** [comment]
Also, this is not tied to release 1.2 as I stated in other issues.  Helm is not a blocker for the release.

**Comment by joshua-rutherford** [comment]
Lastly, this looks like large portions are OBE by #596

**Comment by justincely** [comment]
agreed.  OBE
