### ISSUE TITLE
[release-2.2] Update versions for all Charts

### ISSUE THREAD

**Issue by chrisbsmith** [DecipherNow/helm-charts#560]
All of our helm charts are versioned and the versions are incremented as updates are made to the charts.  However, the versioning construct relates to the version of the Grey Matter chart being deployed. 

For our new `release-2.2` branch, the Grey Matter chart version should be `2.2.X` and all subcharts should too.  

We should make this update sooner than later to keep our versioning structure stays in sync.

For example, here is the version for the jwt chart from the `release-2.2` branch

https://github.com/DecipherNow/helm-charts/blob/27b1b89c9876f84e78583ec8ec46850d249c5327/data/jwt/Chart.yaml#L5

**Comment by moosecanswim** [comment]
@zoemccormick @kaitmore just to make sure you see this

**Comment by moosecanswim** [comment]
@chrisbsmith there is no `greymatter` chart in release 2.2. Instead they are compartmentalized into fabric, sense, and data.

**Comment by moosecanswim** [comment]
PR561
