### ISSUE TITLE
Update ci process to start k3d cluster and helm install mesh

### ISSUE THREAD

**Issue by moosecanswim** [DecipherNow/helm-charts#564]
Currently the ci pipeline only checks that our charts can be built and pushed up to decipher prod nexus.  Investigate adding steps to circleci to stand up a k3d cluster and `make install` the mesh.

https://github.com/punya-asapp/k8s-circleci

If this is successfull our pipeline will ensure the above plus make targets work as well as the mesh can be installed.

we could also leverage the api tester to test endpoints of mesh components

**Comment by chrisbsmith** [comment]
@moosecanswim Familiarize yourself with this: https://github.com/DecipherNow/gm-integrity

That's what you should run against the mesh after it's been deployed.  Though at one point things were hard coded into the image so it may need updates or may not be quite ready for full time use

**Comment by chrisbsmith** [comment]
@danielpcox @hiromis @jsweetland do any of you know if the Docker container for gm-integrity is still hard coded for quick start certs?  (Those have probably expired now anyways)

**Comment by hiromis** [comment]
https://github.com/DecipherNow/gm-integrity/blob/master/Dockerfile#L11 Yes

**Comment by moosecanswim** [comment]
Its been a while that this has been on pause but i came across an article this morning where a developer developed a cirleci orb that will stand up the k3d cluster in circleci.  https://devopsspiral.com/articles/linux/k3d-orb/

**Comment by chrisbsmith** [comment]
@moosecanswim, we actually can close this issue to the work I've been doing on the automated helm testing, https://github.com/DecipherNow/helm-charts/blob/helm-testing/.circleci/config.yml
