### ISSUE TITLE
[release-2.2] Remove all "docker-dev" references before final release

### ISSUE THREAD

**Issue by chrisbsmith** [DecipherNow/helm-charts#579]
PR #565 updated the Helm Charts to deploy control plane 1.3.0, and in doing so, it updated all references to `docker.greymatter.production.deciphernow.com` to `docker-dev.greymatter.production.deciphernow.com`. This is fine for now, but we need to make sure we track the removal of the `-dev` tag as a critical issue before we release `release-2.2` branch of the Helm Charts. 

@justincely @bcmendoza @moosecanswim 

@justincely This should be added as an issue to your 1.2 release plan.

**Comment by justincely** [comment]
:100:  @chrisbsmith.  The initial move to `docker.production` was for POCs before we had given them access to the dev repo.  Coding on release candidates should be against `-dev` and when they are released for GA all images should move to reference production.

**Comment by justincely** [comment]
closed with #667
