### ISSUE TITLE
[release-2.2] If spire is disabled, the spire charts should not be installed

### ISSUE THREAD

**Issue by chrisbsmith** [DecipherNow/helm-charts#588]
I disabled spire to test the cert deployment and the spire agent and server were still deployed. I wouldn't expect these to be deployed. The Makefile should detect this and not deploy spire

**Comment by moosecanswim** [comment]
Hey @hiromis you might wanna check out condition fields https://helm.sh/docs/topics/charts/#tags-and-condition-fields-in-dependencies

**Comment by hiromis** [comment]
That looks like a cleaner approach. I will try it out. Thanks, @moosecanswim!

**Comment by hiromis** [comment]
It seems as though this will work if we were installing spire agent and server as "dependencies" - i.e. if we do not do this https://github.com/DecipherNow/helm-charts/blob/release-2.2/spire/Makefile#L13 and https://github.com/DecipherNow/helm-charts/blob/release-2.2/spire/Makefile#L17 

So to make this work, we will need to helm install the chart in helm-charts/spire/ folder to install both server and agent. But my understanding is that we wanted to install them in a particular order and wait till the server starts. I will just go with the original PR unless you guys have further insights/

**Comment by moosecanswim** [comment]
Ah yes, thats right.  I forgot that we moved to installing the agent and server separately.  Since were doing that can you see if we can remove the `spire/Chart.yaml` and `spire/Chart.lock` as they are not used (and caused me confusion :-) )

**Comment by hiromis** [comment]
> if we can remove the `spire/Chart.yaml` and `spire/Chart.lock` as they are not used (and caused me confusion :-) )

I made an attempt. Could you take a look at https://github.com/DecipherNow/helm-charts/pull/598 and see what you think, @moosecanswim?

**Comment by hiromis** [comment]
Closed by #598
