### ISSUE TITLE
Create helm chart for observables ELK stack

### ISSUE THREAD

**Issue by justincely** [DecipherNow/helm-charts#596]
The full observables feature in Grey Matter requires some supporting infrastructure to deploy.  Though observables can be "turned on" in the mesh only, they need somewhere to go, be scraped, and aggregated to really use them.

This issue is to create a separate chart to deploy a simple ELK stack. This would be intended primarily as a reference architecture, demo capability, and dev capability.  It would be able to be deployed before running the Grey Matter helm charts and then allow turning on observables and seeing a Kibana dashboard.

**Comment by chrismholmes** [comment]
? Didn't @moosecanswim already do this?

**Comment by moosecanswim** [comment]
@justincely @chrismholmes I have this alrady built out for di2e (https://bitbucket.di2e.net/projects/GREYMATTER/repos/helm-charts/browse/observables). It would be a fairly easy lift from openshift to kubernetes

**Comment by chrisbsmith** [comment]
I removed specific customer reference and the url for the charts from @moosecanswim's comment. We can share this directly
