### ISSUE TITLE
s3credentials.template was not updated PR #597

### ISSUE THREAD

**Issue by chrisbsmith** [DecipherNow/helm-charts#629]
PR #597 updated the credentials.template file to allow for multiple docker registries.  However, if a user inputs that they do want to use AWS, it falls to the `s3credentials.template` which was not updated. 
 
https://github.com/DecipherNow/helm-charts/blob/b06dbae59540b57bdf4d1d6f05ea12687a3929b1/ci/scripts/s3credentials.template#L2

@moosecanswim @zoemccormick FYI

**Comment by moosecanswim** [comment]
Ahh, I see what you mean
