### ISSUE TITLE
GM Data does not need to be included in the default Grey Matter installation

### ISSUE THREAD

**Issue by chrisbsmith** [DecipherNow/helm-charts#646]
For a standard Grey Matter installation, Grey Matter Data (not the internal Data), does not need to be included.  PR #645 added the option to include it or not, but for completeness, it should be removed all together and transitioned to it's own chart for easy installations for customer specific namespaces.

The issue is that when it is not enabled, the configMap generation still builds the Grey Matter mesh and Catalog API objects and applies them. So when a dashboard is presented, Grey Matter Data still displays, but is shown as down.

**Comment by zoemccormick** [comment]
closed with #664
