### ISSUE TITLE
template custom SPIRE upstream CA

### ISSUE THREAD

**Issue by zoemccormick** [DecipherNow/helm-charts#661]
Right now, the actual chart files need to be edited in order to configure a custom upstream CA for spire.  We should template this to make it easier and not require a local install.

The necessary steps for this configuration are [here](https://docs.greymatter.io/usage/fabric/security/spire/configuration#configure-an-upstream-ca).

There are a couple of options for this:

In the most ideal case, we include a script that would generate all of the necessary certs using [acert](https://github.com/deciphernow/acert) and places them in the correct place in the charts on the fly.  Josh has instructions [here](https://github.com/joshua-rutherford/greymatter-tutorials/tree/master/kubernetes#deploying-a-spire) on the steps for this.

Another (easier) way to do this for now would be to template [this file](https://github.com/DecipherNow/helm-charts/blob/release-2.2/spire/server/templates/server-ca-secret.yaml) and [this file](https://github.com/DecipherNow/helm-charts/blob/release-2.2/spire/server/templates/server-tls-secret.yaml) the same way that we do the secrets chart, by adding the certs to the values file.  It should be noted that we will also need a value for [this configuration](https://github.com/DecipherNow/helm-charts/blob/15227e846565ee656f03d8fd54c27b63289b6140/spire/server/templates/validatingwebhookconfiguration.yaml#L17).

**Comment by joshua-rutherford** [comment]
fwiw, i provided the following to a customer regarding overriding the template values: https://support.greymatter.io/a/tickets/239

**Comment by zoemccormick** [comment]
@joshua-rutherford these steps worked perfectly for me - I am curious as to why steps 3,4,5 from [these instructions](https://github.com/joshua-rutherford/greymatter-tutorials/tree/master/kubernetes#deploying-a-spire) aren't needed? this info may help when working on this issue

**Comment by joshua-rutherford** [comment]
They aren't required because we baked in some certificates, but never the less should be done.  Having your certificate authority's private key in a helm chart repo basically makes it untrustable.  However, the deployment will work with that setup, it's just not terribly secure.
