### ISSUE TITLE
Edge Service is defined as a LoadBalancer

### ISSUE THREAD

**Issue by chrisbsmith** [DecipherNow/helm-charts#669]
We are making quite the assumption by hard coding the edge service resource as a type `LoadBalancer`. Not only does this cost additional money in the cloud environment (spinning up a separate LB), it quite possibly circumvents the ingress configuration defined by the cluster.

In our documentation, we describe how to configure voyager or nginx-ingress to handle cluster ingress. These two tools manage all inbound traffic, yet when we specify the edge as a LoadBalancer type, it creates it's own ingress path. This should be removed in favor of a type `ClusterIP` (or left blank which defaults to `clusterIP`), as was done in `release-2.1`

https://github.com/DecipherNow/helm-charts/blob/79e1cf58d1c615b77a481e4da2d1000f750f898a/edge/templates/edge-service.yaml#L17

https://github.com/DecipherNow/helm-charts/blob/release-2.1/edge/templates/edge-service.yaml

**Comment by rahug20** [comment]
PR: https://github.com/DecipherNow/helm-charts/pull/691
