### ISSUE TITLE
Passwords and API Keys should be randomized

### ISSUE THREAD

**Issue by chrisbsmith** [DecipherNow/helm-charts#675]
Our Helm Charts create several password based secrets. Many of these require the user to provide a password for something they will rarely interact with. Helm has the ability to create a [random string](https://helm.sh/docs/chart_template_guide/function_list/#randalphanum-randalpha-randnumeric-and-randascii) and we should investigate using this to create our password based secrets. This would also reduce some complexity to the values files. Though, we should allow a user to specify a password if they really want to.

The one draw back is that helm is not smart enough to not recreate the random value for the secret during an upgrade. So each helm upgrade will trigger an update to the secret. [There is a known workaround](https://github.com/helm/charts/issues/5167#issuecomment-641558251) that could be applied to each secret object.

These secrets could be randomly generated:
- [internal redis password](https://github.com/DecipherNow/helm-charts/blob/release-2.2/secrets/values.yaml#L669)
- [redis password](https://github.com/DecipherNow/helm-charts/blob/release-2.2/secrets/values.yaml#L990)
- [mongo root password](https://github.com/DecipherNow/helm-charts/blob/release-2.2/secrets/values.yaml#L25)
- [mongo admin password](https://github.com/DecipherNow/helm-charts/blob/release-2.2/secrets/values.yaml#L27)
- [mongo gm data password](https://github.com/DecipherNow/helm-charts/blob/release-2.2/secrets/values.yaml#L29)
- [internal jwt api key](https://github.com/DecipherNow/helm-charts/blob/release-2.2/secrets/values.yaml#L696)
- [jwt api key](https://github.com/DecipherNow/helm-charts/blob/release-2.2/secrets/values.yaml#L1307)
- [gm data master key](https://github.com/DecipherNow/helm-charts/blob/release-2.2/secrets/values.yaml#L19)
- [internal gm data master key](https://github.com/DecipherNow/helm-charts/blob/release-2.2/secrets/values.yaml#L189)
- [postgres password](https://github.com/DecipherNow/helm-charts/blob/release-2.2/secrets/values.yaml#L511)

**Comment by rahug20** [comment]
PR: https://github.com/DecipherNow/helm-charts/pull/689
