### ISSUE TITLE
Use Helm lookup to determine if docker secret should be created

### ISSUE THREAD

**Issue by chrisbsmith** [DecipherNow/helm-charts#676]
Now that Helm 3 has the ability to look up values from the k8s api, we should leverage this capability when we create the docker.secret. There are some customers that will prescribe an imagePullSecret in our namespace and our charts should be able to take a secret name and check for its existence and not create it if found. 

## Helm lookup function:
- https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function

## File in question:

https://github.com/DecipherNow/helm-charts/blob/a2884f2e18ee98ccd7d842a041329d875d75da08/secrets/templates/docker-secret.yaml

## Possible rewrite:

```yaml
{{- $imagePullSecret := (lookup "v1" "Secret" .Release.Namespace .Values.global.image_pull_secret) }}
{{- if not $imagePullSecret }}

{{- define "registry_auths" }}
{{- $creds := dict "credentials" (list) }}
{{- range $repo := .Values.dockerCredentials }}
{{- $registry := $repo.registry }}
{{- $email := $repo.email }}
{{- $username:= $repo.username }}
{{- $password := $repo.password }}
{{- $b64auth :=  (printf "%s:%s" $username $password | b64enc) }}
{{- $autho := (printf "\"%s\": {\"auth\": \"%s\"}" $registry $b64auth) | append $creds.credentials | set $creds "credentials" }}
{{- end }}
{{- $authos := (join "," $creds.credentials) }}
{{- printf $authos }}
{{- end }}


kind: Secret
apiVersion: v1
metadata:
  name: docker.secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\": {%s}}" (include "registry_auths" .) | b64enc }}
{{/* --- */}}
{{- end }}
```

**Comment by rahug20** [comment]
PR: https://github.com/DecipherNow/helm-charts/pull/688
