### ISSUE TITLE
ImagePullSecret name not being set properly

### ISSUE THREAD

**Issue by chrisbsmith** [DecipherNow/helm-charts#682]
We have the ability for users to define the name of the imagePullSecret that will be used by all charts, specifically by setting `.Values.global.image_pull_secret` https://github.com/DecipherNow/helm-charts/blob/9623b425f72f896d4720187f1af0db4df84a8d60/global.yaml#L3 However, we are not using this value to define the name of the secret the charts create.
 
https://github.com/DecipherNow/helm-charts/blob/9623b425f72f896d4720187f1af0db4df84a8d60/secrets/templates/docker-secret.yaml#L19

Issue #676 can probably be combined in a singe update.

**Comment by rahug20** [comment]
PR: https://github.com/DecipherNow/helm-charts/pull/688
