### ISSUE TITLE
update helm-charts to use redis persisters for gm-catalog and gm-control-api

### ISSUE THREAD

**Issue by justincely** [DecipherNow/helm-charts#686]
additionally, they should use the redis envoy filter when possible.

**Comment by justincely** [comment]
@bcmendoza lets get started on this with `latest` or `dev` images for now.  we can at least get the structure right and in a PR and update to final images before merge

**Comment by bcmendoza** [comment]
1. users can specify connection strings to external resource.  URL, username, password, certs, whatever.  If that's provided, we don't spin up anything in k8s and just attempt to connect.
2. if no connection parameters are provided, then we assume you want one locally.  In that case we spin up a stateful set and the templates would connect to that

**Comment by kaitmore** [comment]
Work has been completed in PR #735, it will be merged once we cut a release.
