### ISSUE TITLE
k3d install script no longer valid

### ISSUE THREAD

**Issue by chrisbsmith** [DecipherNow/helm-charts#706]
k3d has promoted to version 3.0 and the install scripts below is no longer valid.  To install v1.7.0, it should reference. We should try to stay up to date with k3d, but I had issues with our deployment and an edge service of type `ClusterIP`. 

```
https://raw.githubusercontent.com/rancher/k3d/v1.7.0/install.sh
```

https://github.com/DecipherNow/helm-charts/blob/73ccb631a8d267ac3b6dd796cf78991371c6d406/ci/scripts/k3d.sh#L4

**Comment by EddyIV** [comment]
`curl -s https://raw.githubusercontent.com/rancher/k3d/main-v1/install.sh | TAG=v1.7.0 bash` should do it
