### ISSUE TITLE
Question - Spire agent attestation in spire helm.

### ISSUE THREAD

**Issue by PriyaKatkade** [DecipherNow/helm-charts#736]
I am using spire helm chart from this repository. I have performed the steps as mentioned in README. But I am facing problem while issuing identity for agent.
Agent doesn't getting identity from spire server. If I execute **spire-agent api fetch** command in spire-agent container, its giving error "No identity issued". 
Also when k8s-workload-registrar registers workload, spire-agent gives error. If we see log file, it shows error while issuing identity.

Can anyone please tell me why this is happening?

**Comment by joshua-rutherford** [comment]
While the SPIRE Helm chart here may work for you it has been very tailored for Grey Matter deployments and we have not tested it heavily outside that context.  That said, we are interested in the issues you are seeing because this deployment should work out of the box in most cases.

Can you provide logs from the registrar, agent and server?

Also, note that this configuration's ability to operate as planned is predicated on a some Kubernetes features that may not be enabled in all clusters.  It would help to understand what version of Kubernetes you are running and what provider (e.g., EKS) or distribution (e.g., k3s) you are using.

**Comment by PriyaKatkade** [comment]
I am using minikube.
Minikube version: v1.12.3
Kubernetes version: v1.18.3

**Logs**

**agent -**
```
time="2020-09-03T14:38:59Z" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
time="2020-09-03T14:39:17Z" level=error msg="Received error from stream secrets server" error="<nil>" method=stream_secrets subsystem_name=sds_api
```

**server**
`time="2020-09-03T14:38:29Z" level=info msg="Node attestation request completed" address="172.17.0.2:37882" attestor=k8s_psat method=node_api spiffe_id="spiffe://example.org/spire/agent/k8s_psat/example/5f97c121-8ad5-408f-8874-13367e028910" subsystem_name=node_api
`

**registrar**
```
time="2020-09-03T14:38:18Z" level=info msg="Dialing server" socket_path=/run/spire/socket/registration.sock
time="2020-09-03T14:38:18Z" level=info msg="Initializing registrar"
time="2020-09-03T14:38:18Z" level=info msg="Created pod entry" parent_id="spiffe://example.org/spire/server" selectors="k8s_psat:cluster:example" spiffe_id="spiffe://example.org/k8s-workload-registrar/example/node"
time="2020-09-03T14:38:18Z" level=info msg="Serving HTTPS" addr="[::]:8444" skip_client_verification=true
2020/09/03 14:38:28 http: TLS handshake error from 172.17.0.2:45453: EOF
```

I am getting following entry list after registering workloads by k8s-workload-registrar
```
Entry ID      : 953b98e8-9b43-48ad-9b47-d59aa3576c5a
SPIFFE ID     : spiffe://example.org/backend
Parent ID     : spiffe://example.org/k8s-workload-registrar/example/node
TTL           : default
Selector      : k8s:ns:default
Selector      : k8s:pod-name:spire-helm-backend-58c85b64bf-j64k5

Entry ID      : cb46bf14-e5c6-43f6-9e4e-d65387a54de9
SPIFFE ID     : spiffe://example.org/k8s-workload-registrar/example/node
Parent ID     : spiffe://example.org/spire/server
TTL           : default
Selector      : k8s_psat:cluster:example
```
Everything is working as expected, like mTLS communication is established between services. But I am not getting how it works even if agent is not attested.

And here we can see parentID "spiffe://example.org/k8s-workload-registrar/example/node" is there. So this parentID is for which node? This parentID is auto created by k8s-workload-registrar at start-up.

**Comment by joshua-rutherford** [comment]
Given the limited context I can't really speak to what you mean by "mTLS communication between services" as I'm not sure what services you are talking about.  However, this chart relies upon some features that are not turned on by default in Minikube.  Can you confirm that you have started your Minikube per the instructions here: https://spiffe.io/docs/latest/spire/installing/getting-started-k8s/#considerations-when-using-minikube

**Comment by chrisbsmith** [comment]
HI @PriyaKatkade, I'm going to close this since we haven't gotten a response in a bit.  Feel free to reopen if you need additional support.
