### ISSUE TITLE
Invalid Mesh Configurations generated for Prometheus when using quickstart certs

### ISSUE THREAD

**Issue by chrisbsmith** [DecipherNow/helm-charts#743]
When running the helm charts without SPIRE enabled, and using our quickstart certs, requests to Prometheus will fail with a `403`.  The prometheus sidecar will log this entry

```
Impersonation Invalid -> USER_DN: CN=quickstart,OU=Engineering,O=Decipher Technology Studios,L=Alexandria,ST=Virginia,C=US | EXTERNAL_SYS_DN:  | SSL_CLIENT_S_DN: CN=quickstart,OU=Engineering,O=Decipher Technology Studios,L=Alexandria,ST=Virginia,C=US
```

Investigation shows that the Prometheus configurations are set to communicate without TLS, from the edge all the way to prometheus. However, the prometheus listener is configured with an active `gm_impersonation` filter. The `403` error is returned when the proxy attempts to authorize the impersonation DN but there is no certificate passed along from the edge.

Two possible solutions:

1. Update the mesh configuration to perform TLS communication from the edge to the prometheus domain; then non-TLS from the cluster to prometheus (since prometheus is not configured for TLS). 

2. Add an additional check of `services.prometheus.secret.enabled` to the `gm.impersonation` filter and configuration

https://github.com/DecipherNow/helm-charts/blob/b67a59bbe9365774c76b99e9960ad289bf39e4cc/fabric/control-api/json/services/listener.json#L30-L34

https://github.com/DecipherNow/helm-charts/blob/b67a59bbe9365774c76b99e9960ad289bf39e4cc/fabric/control-api/json/services/listener.json#L86-L89

Option 1 is the more correct option to take; to force SSL traffic through out mesh. However, it will be a update to how we define the prometheus configurations. In order to not add anymore complexity to our configurations, the prometheus configurations will probably need to move out the `services` loop and into the `special` directory. This will allow us to "hard code" the configurations necessary to enable TLS mesh communications and non-TLS proxy -> service communication.

**Comment by rahug20** [comment]
done
