### ISSUE TITLE
Update the Readme

### ISSUE THREAD

**Issue by chrisbsmith** [DecipherNow/helm-charts#91]
I was working with an intern to deploy Grey Matter with Helm and found that our README is out of date.  The main README should be a simple guide to deploy the Grey Matter Helm Chart, so it should cover updating values for all requirements.

**Comment by justincely** [comment]
@chrisbsmith is this OBE?  we did a big change to the readme recently.

**Comment by chrisbsmith** [comment]
i'm sure it is.  i'm good to close.
